server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-microservices
          uri: http://localhost:8002
          predicates:
            - Path=/api/v1.0/user/**
        - id: product-microservices
          uri: http://localhost:8001
          predicates:
            - Path=/api/v1.0/product/**
        - id: helpandsupport-microservices
          uri: http://localhost:8003
          predicates:
            - Path=/api/v1.0/help&support/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders:
              - "Origin"
              - "Content-Type"
              - "Accept"
              - "Authorization"
              - "User-Key"
              - "Request-Tracker"
              - "Session-Tracker"
              - "X-XSRF-TOKEN"
              - "X-IBM-CLIENT-ID"
              - "Message-ID"
              - "X-IBM-CLIENT-SECRET"
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
