server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-microservices
          uri: http://localhost:8002
          predicates:
            - Path=/api/v1.0/user/**
        - id: product-microservices
          uri: http://localhost:8001
          predicates:
            - Path=/api/v1.0/product/**
